---
title: "JSON transformation"
author: "Xinhui Zhang"
date: "2024-11-14"
output: html_document
---

```{r}
library(jsonlite)
```

```{r}
setwd("~/Documents/GitHub/MC_data_cleaning/W23 Rubric Item Data")
json_data <- read_json("~/Documents/GitHub/MC_data_cleaning/W23 Rubric Item Data/Exam 1A-rubric.json", simplifyVector = TRUE)
```


## Exam 1
```{r}
library(jsonlite)
library(dplyr)

file_paths <- list.files(path = "~/Documents/GitHub/MC_data_cleaning/W23 Rubric Item Data/Exam 1", pattern = "\\.json$", full.names = TRUE)


all_students_list <- list()

for (file_path in file_paths) {
  
  json_data <- fromJSON(file_path, flatten = FALSE)
  
  students_list <- list()

  for (question_id in names(json_data)) {
    question <- json_data[[question_id]]
    
  
    for (variable_name in names(question)) {
      variable <- question[[variable_name]]
      
   
      if (is.list(variable)) {
        for (answer_type in names(variable)) {
          answer_data <- variable[[answer_type]]

          if (is.list(answer_data) && !is.null(answer_data$students)) {
           
            for (student in answer_data$students) {
              student_df <- data.frame(
                student = student,
                question_id = question_id,
                variable_name = variable_name,
                answer_type = answer_type,
                file_name = basename(file_path), 
                stringsAsFactors = FALSE
              )
              students_list[[length(students_list) + 1]] <- student_df
            }
          } else if (is.character(answer_data)) {
            print(paste("String data encountered in", question_id, variable_name, answer_type, ":", answer_data))
          } else {
            print(paste("Unexpected data format in", question_id, variable_name, answer_type))
          }
        }
      }
    }
  }

  if (length(students_list) > 0) {
    all_students_list[[length(all_students_list) + 1]] <- bind_rows(students_list)
  }
}

final_df1 <- bind_rows(all_students_list)
```

```{r}
write.csv(file = "json_transformation_Exam_1.csv", final_df1)
```
## Exam 2
```{r}
library(jsonlite)
library(dplyr)

file_paths <- list.files(path = "~/Documents/GitHub/MC_data_cleaning/W23 Rubric Item Data/Exam 2", pattern = "\\.json$", full.names = TRUE)

all_students_list <- list()

for (file_path in file_paths) {
  json_data <- fromJSON(file_path, flatten = FALSE)
  students_list <- list()
  for (question_id in names(json_data)) {
    question <- json_data[[question_id]]
    
    for (variable_name in names(question)) {
      variable <- question[[variable_name]]
      
      if (is.list(variable)) {
        
        for (answer_type in names(variable)) {
          answer_data <- variable[[answer_type]]
          
          if (is.list(answer_data) && !is.null(answer_data$students)) {
            for (student in answer_data$students) {
              student_df <- data.frame(
                student = student,
                question_id = question_id,
                variable_name = variable_name,
                answer_type = answer_type,
                file_name = basename(file_path),  
                stringsAsFactors = FALSE
              )
              students_list[[length(students_list) + 1]] <- student_df
            }
          } else if (is.character(answer_data)) {
            print(paste("String data encountered in", question_id, variable_name, answer_type, ":", answer_data))
          } else {
            print(paste("Unexpected data format in", question_id, variable_name, answer_type))
          }
        }
      }
    }
  }
  if (length(students_list) > 0) {
    all_students_list[[length(all_students_list) + 1]] <- bind_rows(students_list)
  }
}
final_df2 <- bind_rows(all_students_list)

View(final_df2)
```

```{r}
write.csv(file = "json_transformation_Exam_2.csv", final_df2)
```

## Exam 3
```{r}
library(jsonlite)
library(dplyr)

file_paths <- list.files(path = "~/Documents/GitHub/MC_data_cleaning/W23 Rubric Item Data/Exam 3", pattern = "\\.json$", full.names = TRUE)

all_students_list <- list()

for (file_path in file_paths) {
  json_data <- fromJSON(file_path, flatten = FALSE)
  students_list <- list()
  for (question_id in names(json_data)) {
    question <- json_data[[question_id]]
    
    for (variable_name in names(question)) {
      variable <- question[[variable_name]]
      
      if (is.list(variable)) {
        
        for (answer_type in names(variable)) {
          answer_data <- variable[[answer_type]]
          
          if (is.list(answer_data) && !is.null(answer_data$students)) {
            for (student in answer_data$students) {
              student_df <- data.frame(
                student = student,
                question_id = question_id,
                variable_name = variable_name,
                answer_type = answer_type,
                file_name = basename(file_path),  
                stringsAsFactors = FALSE
              )
              students_list[[length(students_list) + 1]] <- student_df
            }
          } else if (is.character(answer_data)) {
            print(paste("String data encountered in", question_id, variable_name, answer_type, ":", answer_data))
          } else {
            print(paste("Unexpected data format in", question_id, variable_name, answer_type))
          }
        }
      }
    }
  }
  if (length(students_list) > 0) {
    all_students_list[[length(all_students_list) + 1]] <- bind_rows(students_list)
  }
}
final_df3 <- bind_rows(all_students_list)

View(final_df3)
```

```{r}
write.csv(file = "json_transformation_Exam_3.csv", final_df3)
```

## Exam 4
```{r}
library(jsonlite)
library(dplyr)

file_paths <- list.files(path = "~/Documents/GitHub/MC_data_cleaning/W23 Rubric Item Data/Exam 4", pattern = "\\.json$", full.names = TRUE)

all_students_list <- list()

for (file_path in file_paths) {
  json_data <- fromJSON(file_path, flatten = FALSE)
  students_list <- list()
  for (question_id in names(json_data)) {
    question <- json_data[[question_id]]
    
    for (variable_name in names(question)) {
      variable <- question[[variable_name]]
      
      if (is.list(variable)) {
        
        for (answer_type in names(variable)) {
          answer_data <- variable[[answer_type]]
          
          if (is.list(answer_data) && !is.null(answer_data$students)) {
            for (student in answer_data$students) {
              student_df <- data.frame(
                student = student,
                question_id = question_id,
                variable_name = variable_name,
                answer_type = answer_type,
                file_name = basename(file_path),  
                stringsAsFactors = FALSE
              )
              students_list[[length(students_list) + 1]] <- student_df
            }
          } else if (is.character(answer_data)) {
            print(paste("String data encountered in", question_id, variable_name, answer_type, ":", answer_data))
          } else {
            print(paste("Unexpected data format in", question_id, variable_name, answer_type))
          }
        }
      }
    }
  }
  if (length(students_list) > 0) {
    all_students_list[[length(all_students_list) + 1]] <- bind_rows(students_list)
  }
}
final_df4 <- bind_rows(all_students_list)

View(final_df4)
```

```{r}
write.csv(file = "json_transformation_Exam_4.csv", final_df4)
```

## Exam 5
```{r}
library(jsonlite)
library(dplyr)

file_paths <- list.files(path = "~/Documents/GitHub/MC_data_cleaning/W23 Rubric Item Data/Exam 5", pattern = "\\.json$", full.names = TRUE)

all_students_list <- list()

for (file_path in file_paths) {
  json_data <- fromJSON(file_path, flatten = FALSE)
  students_list <- list()
  for (question_id in names(json_data)) {
    question <- json_data[[question_id]]
    
    for (variable_name in names(question)) {
      variable <- question[[variable_name]]
      
      if (is.list(variable)) {
        
        for (answer_type in names(variable)) {
          answer_data <- variable[[answer_type]]
          
          if (is.list(answer_data) && !is.null(answer_data$students)) {
            for (student in answer_data$students) {
              student_df <- data.frame(
                student = student,
                question_id = question_id,
                variable_name = variable_name,
                answer_type = answer_type,
                file_name = basename(file_path),  
                stringsAsFactors = FALSE
              )
              students_list[[length(students_list) + 1]] <- student_df
            }
          } else if (is.character(answer_data)) {
            print(paste("String data encountered in", question_id, variable_name, answer_type, ":", answer_data))
          } else {
            print(paste("Unexpected data format in", question_id, variable_name, answer_type))
          }
        }
      }
    }
  }
  if (length(students_list) > 0) {
    all_students_list[[length(all_students_list) + 1]] <- bind_rows(students_list)
  }
}
final_df5 <- bind_rows(all_students_list)

View(final_df5)
```

```{r}
write.csv(file = "json_transformation_Exam 5.csv", final_df5)
```

### seperate the name and email and grader
## put them into 3 columns

```{r}
library(dplyr)

final_df1 <- final_df1 %>%
  filter(student != "Student's name Sections Graded time Last graded by")
```

```{r}
library(dplyr)
library(stringr)
final1_data <- final_df1 %>%
  mutate(name = paste(word(student, 1), word(student, 2))) %>%
  select(name, everything()) 
```




```{r}
library(dplyr)
library(stringr)

grade_data <- final1_data %>%
  mutate(grader = paste(word(student, -2), word(student, -1))) %>%
  select(grader, everything()) 

```

```{r}
grade_data <- grade_data[-1, ]
```

```{r}
library(tidyr)

email <- grade_data %>%
  separate(student, into = c("part1", "email", "part3"), sep = "\\(", extra = "merge") %>%
  separate(email, into = c("email"), sep = "\\)", extra = "drop") %>%
  select(email, everything()) 

```

```{r}
email <- email %>%
  select(-part1, -part3)
```

