---
title: "Exam1Clean"
author: "Xinhui Zhang"
date: "2025-04-21"
output: html_document
---


# Exam 1

```{r}
library(dplyr)
library(stringr)
library(tidyverse)
```

```{r}
setwd("~/GitHub/MC_data_cleaning/W23 Rubric Item Data")
#setwd("~/Documents/GitHub/MC_data_cleaning/W23 Rubric Item Data")
df <- read.csv("json_transformation_Exam_1.csv")
```

```{r}
df_clean <- df %>%
  filter(student != "Student's name Sections Graded time Last graded by")

df_clean <- df_clean %>%
  select(-variable_name, -answer_type)

head(df_clean)
```

```{r}
df_1 <- df_clean %>%
  mutate(name = str_extract(student, "^[^\\(]+"),
         email = str_extract(student, "(?<=\\().+?(?=\\))")) %>%
  select(-student) 

length(unique(df_1$name))


```

```{r}
write.csv(df_1, "cleaned_with_name_email.csv", row.names = FALSE)
```

```{r}
df_filtered <- df_1 %>%
  filter(
    grepl("1: H0", question_id, ignore.case = TRUE) |
    grepl("H1: Directional", question_id, ignore.case = TRUE) |
    grepl("PV OP-Def", question_id, ignore.case = TRUE)|
    grepl("OV OP-Def", question_id, ignore.case = TRUE)
  ) %>% mutate(question_id = case_when(grepl("H0", question_id)~ "H0", grepl("OP", question_id)~"OPDEF", grepl("H1", question_id)~"H1", .default = question_id)) %>% mutate(version = case_when(grepl("A", file_name, ignore.case = F)~ "A", grepl("B", file_name, , ignore.case = F)~ "B", grepl("C", file_name, , ignore.case = F)~ "C", grepl("D", file_name, , ignore.case = F)~ "D", .default = file_name)) %>% select(-file_name)
                                      

```


```{r}
setwd("~/GitHub/MC_data_cleaning/DataCleaning")
#setwd("~/Documents/GitHub/MC_data_cleaning/DataCleaning")
roster <- read.csv("df1_with_anonid.csv")



roster <- roster %>%
  rename(name = Full.NAME) %>%
  mutate(name = str_trim(name))

df_filtered <- df_filtered %>%
  mutate(name = str_trim(name))

exam_with_anon <- df_filtered %>%
  left_join(roster %>% select(name, student_id, anon_id), by = "name")

length(unique(exam_with_anon$anon_id))
head(exam_with_anon)
```

```{r}
exam_with_anon_clean <- exam_with_anon %>%
  filter(!is.na(anon_id))
```

#get rid of the specific answer columns


```{r}
exam_with_anon_clean1 <- exam_with_anon_clean %>%
  filter(!toupper(str_trim(Notation)) %in% c(
    "CH01A", "CH02A", "CH03A", "VDH11", "VDH13", "CH11", "DH11",
    "OPM1", "OP1", "OPMS1", "OPD1", "OPD2",
    "OVPV1A", "OVPV1D", "OVPV1E", "OVPV2A", "OVPV2B",
    "OVPV3A", "OVPV3B", "IVTM1", "IR1",
    "CCV1A", "CCV1B", "CCV2A", "CCV2B", "CCV3A", "CCV3B",
    "C01A", "C02A", "C03A", "C03B",
    "IT1A", "IT2A", "IT2B", "IT3A", "IT3B",
    "R01A", "R02A", "R03A", "R03B"
  ))%>% select(-name, -email, -X) %>% mutate(exam = 1)
```


```{r}
write.csv(exam_with_anon_clean1, "Exam1_FinalCleaned.csv", row.names = FALSE)
```


#Exam 2

```{r}
setwd("~/GitHub/MC_data_cleaning/W23 Rubric Item Data")
#setwd("~/Documents/GitHub/MC_data_cleaning/W23 Rubric Item Data")
df2 <- read.csv("json_transformation_Exam_2.csv")
```

```{r}
df_clean2 <- df2 %>%
  filter(student != "Student's name Sections Graded time Last graded by")

df_clean2 <- df_clean2 %>%
  select(-variable_name, -answer_type)

head(df_clean2)
```

```{r}
df_2 <- df_clean2 %>%
  mutate(name = str_extract(student, "^[^\\(]+"),
         email = str_extract(student, "(?<=\\().+?(?=\\))")) %>%
  select(-student) 
```

```{r}
df_filtered2 <- df_2 %>%
  filter(
    grepl("1: H0", question_id, ignore.case = TRUE) |
    grepl("H1 Directional", question_id, ignore.case = TRUE) |
    grepl("PV OP-Def", question_id, ignore.case = TRUE)|
    grepl("OV OP-Def", question_id, ignore.case = TRUE)|
    grepl("OV Construct Validity", question_id) |
    grepl("PV Construct Validity", question_id) |
    grepl("Interpretation", question_id)
  ) %>% mutate(question_id = case_when(question_id = grepl("H0", question_id)~ "H0", grepl("OP", question_id)~"OPDEF", grepl("H1", question_id)~"H1", grepl("Construct", question_id)~"CV", grepl("Interpret", question_id)~"Interpret",  .default = question_id))%>% mutate(version = case_when(grepl("A", file_name, ignore.case = F)~ "A", grepl("B", file_name, , ignore.case = F)~ "B", grepl("C", file_name, , ignore.case = F)~ "C", grepl("D", file_name, , ignore.case = F)~ "D", .default = file_name)) %>% select(-file_name)
```

```{r}
library(dplyr)
library(stringr)
setwd("~/GitHub/MC_data_cleaning/DataCleaning")
#setwd("~/Documents/GitHub/MC_data_cleaning/DataCleaning")
roster <- read.csv("df1_with_anonid.csv")



roster <- roster %>%
  rename(name = Full.NAME) %>%
  mutate(name = str_trim(name))

df_filtered2 <- df_filtered2 %>%
  mutate(name = str_trim(name))

exam_with_anon2 <- df_filtered2 %>%
  left_join(roster %>% select(name,student_id, anon_id), by = "name") 

length(unique(exam_with_anon2$anon_id))
head(exam_with_anon2)
```
```{r}
exam_with_anon_clean2a <- exam_with_anon2 %>%
  filter(!is.na(anon_id))
```

```{r}
exam_with_anon_clean2a <- exam_with_anon_clean2a %>%
  filter(!toupper(str_trim(Notation)) %in% c(
    "CH01A", "CH02A", "CH03A", "VDH11", "VDH13", "CH11", "DH11",
    "OPM1", "OP1", "OPMS1", "OPD1", "OPD2",
    "OVPV1A", "OVPV1D", "OVPV1E", "OVPV2A", "OVPV2B",
    "OVPV3A", "OVPV3B", "IVTM1", "IR1",
    "CCV1A", "CCV1B", "CCV2A", "CCV2B", "CCV3A", "CCV3B",
    "C01A", "C02A", "C03A", "C03B",
    "IT1A", "IT2A", "IT2B", "IT3A", "IT3B",
    "R01A", "R02A", "R03A", "R03B"
  )) %>% select(-name, -email, -X) %>% mutate(exam = 2)

View(exam_with_anon_clean2a)
```


```{r}
write.csv(exam_with_anon_clean2a, "Exam2_FinalCleaned.csv", row.names = FALSE)
```


#Exam 3

```{r}
setwd("~/GitHub/MC_data_cleaning/W23 Rubric Item Data")
#setwd("~/Documents/GitHub/MC_data_cleaning/W23 Rubric Item Data")
df3 <- read.csv("json_transformation_Exam_3.csv")
```

```{r}
df_clean3 <- df3 %>%
  filter(student != "Student's name Sections Graded time Last graded by")

df_clean3 <- df_clean3 %>%
  select(-variable_name, -answer_type)

head(df_clean3)
```

```{r}
df_3 <- df_clean3 %>%
  mutate(name = str_extract(student, "^[^\\(]+"),
         email = str_extract(student, "(?<=\\().+?(?=\\))")) %>%
  select(-student) 

length(unique(df_3$name))

```


```{r}
df_filtered3 <- df_3 %>%
  filter(
     grepl("Operational", question_id, ignore.case = TRUE)|
    grepl("Construct Validity", question_id) |
    grepl("Interpretation", question_id) |
    grepl("Confound", question_id)
  ) %>% mutate(question_id = case_when(question_id = grepl("Operational", question_id)~"OPDEF", grepl("Confound", question_id)~"CONFOUND", grepl("Compare", question_id)~"COMPCV", grepl("Construct", question_id)~"CV", grepl("Interpret", question_id)~"Interpret",  .default = question_id))%>% mutate(version = case_when(grepl("A", file_name, ignore.case = F)~ "A", grepl("B", file_name, , ignore.case = F)~ "B", grepl("C", file_name, , ignore.case = F)~ "C", grepl("D", file_name, , ignore.case = F)~ "D", .default = file_name)) %>% select(-file_name)
```

```{r}
library(dplyr)
library(stringr)

setwd("~/GitHub/MC_data_cleaning/DataCleaning")
#setwd("~/Documents/GitHub/MC_data_cleaning/DataCleaning")
roster <- read.csv("df1_with_anonid.csv")



roster <- roster %>%
  rename(name = Full.NAME) %>%
  mutate(name = str_trim(name))

df_filtered3 <- df_filtered3 %>%
  mutate(name = str_trim(name))

exam_with_anon3 <- df_filtered3 %>%
  left_join(roster %>% select(name, student_id, anon_id), by = "name")

length(unique(exam_with_anon3$name))

head(exam_with_anon3)
```

```{r}
exam_with_anon_clean3a <- exam_with_anon3 %>%
  filter(!is.na(anon_id))
```

```{r}
exam_with_anon_clean3a <- exam_with_anon_clean3a %>%
  filter(!toupper(str_trim(Notation)) %in% c(
    "CH01A", "CH02A", "CH03A", "VDH11", "VDH13", "CH11", "DH11",
    "OPM1", "OP1", "OPMS1", "OPD1", "OPD2",
    "OVPV1A", "OVPV1D", "OVPV1E", "OVPV2A", "OVPV2B",
    "OVPV3A", "OVPV3B", "IVTM1", "IR1",
    "CCV1A", "CCV1B", "CCV2A", "CCV2B", "CCV3A", "CCV3B",
    "C01A", "C02A", "C03A", "C03B",
    "IT1A", "IT2A", "IT2B", "IT3A", "IT3B",
    "R01A", "R02A", "R03A", "R03B"
  ))%>% select(-name, -email, -X)%>% mutate(exam = 3)

View(exam_with_anon_clean3a)
```


```{r}
write.csv(exam_with_anon_clean3a, "Exam3_FinalCleaned.csv", row.names = FALSE)
```


#Exam 4
```{r}
setwd("~/GitHub/MC_data_cleaning/W23 Rubric Item Data")
#setwd("~/Documents/GitHub/MC_data_cleaning/W23 Rubric Item Data")
df4 <- read.csv("json_transformation_Exam_4.csv")
```

```{r}
df_clean4 <- df4 %>%
  filter(student != "Student's name Sections Graded time Last graded by")

df_clean4 <- df_clean4 %>%
  select(-variable_name, -answer_type)

head(df_clean4)
```

```{r}
df_4 <- df_clean4 %>%
  mutate(name = str_extract(student, "^[^\\(]+"),
         email = str_extract(student, "(?<=\\().+?(?=\\))")) %>%
  select(-student) 
length(unique(df_4$name))
```


```{r}
df_filtered4 <- df_4 %>%
  filter(
    grepl("OP Def", question_id) |
    grepl("CV", question_id) |
    grepl("12: Confound", question_id) |
    grepl("Internal Threat", question_id) |
    grepl("Replication", question_id)
  ) %>% mutate(question_id = case_when(question_id = grepl("OP", question_id)~"OPDEF", grepl("Confound", question_id)~"CONFOUND",  grepl("CV", question_id)~"CV", grepl("Compare", question_id)~"COMPCV", grepl("Internal", question_id)~"IVTHREAT", grepl("Replication", question_id)~"REP", grepl("Interpret", question_id)~"Interpret", .default = question_id)) %>% mutate(version = case_when(grepl("A", file_name, ignore.case = F)~ "A", grepl("B", file_name, , ignore.case = F)~ "B", grepl("C", file_name, , ignore.case = F)~ "C", grepl("D", file_name, , ignore.case = F)~ "D", .default = file_name)) %>% select(-file_name)
```

```{r}
library(dplyr)
library(stringr)

setwd("~/GitHub/MC_data_cleaning/DataCleaning")
#setwd("~/Documents/GitHub/MC_data_cleaning/DataCleaning")
roster <- read.csv("df1_with_anonid.csv")



roster <- roster %>%
  rename(name = Full.NAME) %>%
  mutate(name = str_trim(name))

df_filtered4 <- df_filtered4 %>%
  mutate(name = str_trim(name))

exam_with_anon4 <- df_filtered4 %>%
  left_join(roster %>% select(name, student_id, anon_id), by = "name")

length(unique(exam_with_anon4$name))
#head(exam_with_anon4)
```

```{r}
exam_with_anon_clean4a <- exam_with_anon4 %>%
  filter(!is.na(anon_id))
```

```{r}
exam_with_anon_clean4a <- exam_with_anon_clean4a %>%
  filter(!toupper(str_trim(Notation)) %in% c(
    "CH01A", "CH02A", "CH03A", "VDH11", "VDH13", "CH11", "DH11",
    "OPM1", "OP1", "OPMS1", "OPD1", "OPD2",
    "OVPV1A", "OVPV1D", "OVPV1E", "OVPV2A", "OVPV2B",
    "OVPV3A", "OVPV3B", "IVTM1", "IR1",
    "CCV1A", "CCV1B", "CCV2A", "CCV2B", "CCV3A", "CCV3B",
    "C01A", "C02A", "C03A", "C03B",
    "IT1A", "IT2A", "IT2B", "IT3A", "IT3B",
    "R01A", "R02A", "R03A", "R03B"
  ))%>% select(-name, -email, -X) %>% mutate(exam = 4)

View(exam_with_anon_clean4a)
```


```{r}
write.csv(exam_with_anon_clean4a, "Exam4_FinalCleaned.csv", row.names = FALSE)
```

#Exam 5

```{r}
setwd("~/GitHub/MC_data_cleaning/W23 Rubric Item Data")
#setwd("~/Documents/GitHub/MC_data_cleaning/W23 Rubric Item Data")
df5 <- read.csv("json_transformation_Exam_5.csv")
```

```{r}
df_clean5 <- df5 %>%
  filter(student != "Student's name Sections Graded time Last graded by")

df_clean5 <- df_clean5 %>%
  select(-variable_name, -answer_type)

#head(df_clean5)
```

```{r}
df_5 <- df_clean5 %>%
  mutate(name = str_extract(student, "^[^\\(]+"),
         email = str_extract(student, "(?<=\\().+?(?=\\))")) %>%
  select(-student) 
```


```{r}
df_filtered5 <- df_5 %>%
  filter(
    grepl("OP Def", question_id) |
    grepl("CV", question_id) |
    grepl("Confound", question_id) |
    grepl("Internal Threat", question_id) |
    grepl("Replication", question_id)|
    grepl("Interpretation", question_id)
  ) %>% mutate(question_id = case_when(question_id = grepl("OP", question_id)~"OPDEF", grepl("Confound", question_id)~"CONFOUND",  grepl("PV CV", question_id)~"CV", grepl("Compare", question_id)~"COMPCV", grepl("Internal", question_id)~"IVTHREAT", grepl("Replication", question_id)~"REP", grepl("Interpret", question_id)~"Interpret", .default = question_id)) %>% mutate(version = case_when(grepl("A", file_name, ignore.case = F)~ "A", grepl("B", file_name, , ignore.case = F)~ "B", grepl("C", file_name, , ignore.case = F)~ "C", grepl("D", file_name, , ignore.case = F)~ "D", .default = file_name)) %>% select(-file_name)

```

```{r}
library(dplyr)
library(stringr)

setwd("~/GitHub/MC_data_cleaning/DataCleaning")
#setwd("~/Documents/GitHub/MC_data_cleaning/DataCleaning")
roster <- read.csv("df1_with_anonid.csv")



roster <- roster %>%
  rename(name = Full.NAME) %>%
  mutate(name = str_trim(name))

df_filtered5 <- df_filtered5 %>%
  mutate(name = str_trim(name))

exam_with_anon5 <- df_filtered5 %>%
  left_join(roster %>% select(name, student_id, anon_id), by = "name")


head(exam_with_anon5)
```

```{r}
exam_with_anon_clean5a <- exam_with_anon5 %>%
  filter(!is.na(anon_id))
```

```{r}
exam_with_anon_clean5a <- exam_with_anon_clean5a %>%
  filter(!toupper(str_trim(Notation)) %in% c(
    "CH01A", "CH02A", "CH03A", "VDH11", "VDH13", "CH11", "DH11",
    "OPM1", "OP1", "OPMS1", "OPD1", "OPD2",
    "OVPV1A", "OVPV1D", "OVPV1E", "OVPV2A", "OVPV2B",
    "OVPV3A", "OVPV3B", "IVTM1", "IR1",
    "CCV1A", "CCV1B", "CCV2A", "CCV2B", "CCV3A", "CCV3B",
    "C01A", "C02A", "C03A", "C03B",
    "IT1A", "IT2A", "IT2B", "IT3A", "IT3B",
    "R01A", "R02A", "R03A", "R03B"
  ))%>% select(-name, -email, -X) %>% mutate(exam = 5)

View(exam_with_anon_clean5a)
```


```{r}
write.csv(exam_with_anon_clean5a, "Exam5_FinalCleaned.csv", row.names = FALSE)
```



```{r}

rubric_data <- rbind(exam_with_anon_clean1, exam_with_anon_clean2a, exam_with_anon_clean3a, exam_with_anon_clean4a, exam_with_anon_clean5a)

write.csv(rubric_data, file = "full_rubric_data.csv", row.names = F)


```

# calculating variables 


# Mistakes Per Exam Per Question Per Student 


```{r}


rubric_data <- read.csv(file = "full_rubric_data.csv")


rubric_data <- rubric_data %>% mutate(question_id = as.factor(str_trim(question_id)))
rubric_data <- rubric_data %>% mutate(student_id = as.factor(str_trim(student_id)))

rubric_data <- rubric_data %>% mutate(Notation = as.factor(str_trim(Notation)))
rubric_data <- rubric_data %>% mutate(exam = as.factor(exam))


test <- unique(rubric_data)


mistest <- test %>% group_by(student_id, exam, question_id, Notation)

#Raw value of # of mistakes does not account for repeated items across exams 
mistakes <- rubric_data %>% group_by(student_id, exam, question_id, Notation) %>% summarise(
  count = n()
) %>% mutate(count = case_when(count > 1 ~ 1, .default = count))


#write.csv(mistakes, file = "test.csv")


view(mistakes)

ExamMistakes <- mistakes %>% group_by(student_id, exam) %>% summarise(
  numMistakes = sum(count) # unique rubric items given on that exam 
)
view(ExamMistakes)

QMistakes <- mistakes %>% group_by(student_id, exam, question_id) %>% summarise(
  numMistakes = sum(count) # number of unique items given on that question on each exam 
)
view(QMistakes)

write.csv(QMistakes, file = "Qmistakes.csv")




```





#Data

```{r}

agdata <- read.csv("agdata.csv")

agdata$student_id <- as.factor(agdata$student_id)


#agdata <- agdata %>% mutate(attempt = case_when(question_id == "COMPCV"  ~ 1, .default = attempt ))
#write.csv(agdata, "agdata.csv", row.names = F)

Exam1data <- mistakes %>% filter(exam == 1)
Exam2data <- mistakes %>% filter(exam == 2) 
Exam3data <- mistakes %>% filter(exam == 3) 
Exam4data <- mistakes %>% filter(exam == 4) 
Exam5data <- mistakes %>% filter(exam == 5) 

```

# repeated mistakes!! 
```{r}
# Time 1 

time1shared <- full_join(Exam1data, Exam2data, by = c("student_id", "Notation"), suffix = c("1" , "2"))%>% select( -exam1, -exam2) %>% mutate(question_id = case_when(is.na(question_id1) ~ question_id2, .default = question_id1)) %>% select(-question_id1, -question_id2)

time1data <- time1shared %>% mutate(rep = count1 + count2 - 1) %>% filter(!is.na(rep)) 

time1mis <- time1data %>% group_by(student_id,question_id) %>% summarise(
  numRep = sum(rep)
) %>% mutate(time = 1) 



# Time 2 

time2shared <- full_join(time1shared, Exam3data, by = c("student_id", "Notation"), suffix = c("1" , "2")) %>% select( -exam) %>% mutate(question_id = case_when(is.na(question_id1) ~ question_id2, .default = question_id1)) %>% mutate(count3 = count) %>% select(-question_id1, -question_id2, -count)

time2data <- time2shared %>% mutate(RepExam1 = count1 + count3 - 1) %>%  mutate(RepExam2 = count2 + count3 - 1) %>%  mutate(rep = case_when(!is.na(RepExam1) ~ 1, !is.na(RepExam2)~1, .default = NA )) %>% filter(!is.na(rep)) 

time2mis <- time2data %>% group_by(student_id,question_id) %>% summarise(
  numRep = sum(rep)
) %>% mutate(time = 2)



# Time 3 

time3shared <- full_join(time2shared, Exam4data, by = c("student_id", "Notation"), suffix = c("1" , "2")) %>% select( -exam) %>% mutate(question_id = case_when(is.na(question_id1) ~ question_id2, .default = question_id1))%>% mutate(count4 = count) %>% select(-question_id1, -question_id2, -count)

time3data <- time3shared %>% mutate(RepExam1 = count1 + count4 - 1) %>%  mutate(RepExam2 = count2 + count4 - 1) %>%  mutate(RepExam3 = count3 + count4 - 1)%>%  mutate(rep = case_when(!is.na(RepExam1) ~ 1, !is.na(RepExam2)~1, !is.na(RepExam3)~1, .default = NA )) %>% filter(!is.na(rep)) #%>% select(-question_id2)

time3mis <- time3data %>% group_by(student_id,question_id) %>% summarise(
  numRep = sum(rep)
) %>% mutate(time = 3)

# Time 4 

time4shared <- full_join(time3shared, Exam5data, by = c("student_id", "Notation"), suffix = c("1" , "2")) %>% select( -exam) %>% mutate(question_id = case_when(is.na(question_id1) ~ question_id2, .default = question_id1))%>% mutate(count5 = count) %>% select(-question_id1, -question_id2, -count)

time4data <- time4shared %>% mutate(RepExam1 = count1 + count5 - 1) %>%  mutate(RepExam2 = count2 + count5 - 1) %>%  mutate(RepExam3 = count3 + count5 - 1)%>%  mutate(RepExam4 = count4 + count5 - 1)%>% mutate(rep = case_when(!is.na(RepExam1) ~ 1, !is.na(RepExam2)~1, !is.na(RepExam3)~1, !is.na(RepExam4)~1,.default = NA )) %>% filter(!is.na(rep)) #%>% select(-question_id2)

time4mis <- time4data %>% group_by(student_id,question_id) %>% summarise(
  numRep = sum(rep)
) %>% mutate(time = 4)


fullmis <- rbind(time1mis, time2mis, time3mis, time4mis)

fullrep <- left_join(rubric_data, time1data, by = c("student_id", "question_id", "Notation"))

fullrep <- left_join(fullrep, time2data, by = c("student_id", "question_id", "Notation"), suffix = c(".1", ".2"))

fullrep <- left_join(fullrep, time3data, by = c("student_id", "question_id", "Notation"), suffix = c(".2", ".3"))
fullrep <- left_join(fullrep, time4data, by = c("student_id", "question_id", "Notation"), suffix = c(".3", ".4"))


fullrep <- fullrep %>% mutate(rep.1 = case_when(is.na(rep.1)~0, .default = rep.1)) %>% mutate(rep.2 = case_when(is.na(rep.2)~0, .default = rep.2)) %>% mutate(rep.3 = case_when(is.na(rep.3)~0, .default = rep.3)) %>% mutate(rep.4 = case_when(is.na(rep.4)~0, .default = rep.4)) %>% mutate(reps = rep.1 + rep.2 + rep.3 + rep.4)

reps <- unique(fullrep) %>% select(anon_id, student_id, question_id, Notation, rep.1, rep.2, rep.3, rep.4, reps)

reps <- unique(reps)


studentreps <- reps %>% group_by(student_id, question_id) %>% summarise(
  rep.1 = sum(rep.1), 
  rep.2 = sum(rep.2),
  rep.3 = sum(rep.3), 
  rep.4 = sum(rep.4), 
)

lreps <- studentreps %>% gather(key = "time", value = "rep", rep.1, rep.2, rep.3, rep.4 )



#write.csv(fullmis, "test.csv", row.names = F)
```


# Add Repeated mistakes to dataset 
```{r}
agdata_ <- left_join(agdata, fullmis, by = c("student_id", "question_id", "time")) 

agdata1 <- agdata_ %>% filter(time == 1) %>% mutate(numRep = case_when(is.na(numRep)~0, .default = numRep))

agdata2 <- agdata_ %>% filter(time == 2) %>% mutate(numRep = case_when(is.na(numRep)~0, .default = numRep))

agdata3 <- agdata_ %>% filter(time == 3) %>% mutate(numRep = case_when(is.na(numRep)~0, .default = numRep))

agdata4 <- agdata_ %>% filter(time == 4) %>% mutate(numRep = case_when(is.na(numRep)~0, .default = numRep))


agdata_temp <- rbind(agdata1, agdata2, agdata3, agdata4)


agdata <- left_join(agdata, agdata_temp, by = c("student_id", "question_id", "time", "attempt"))

```

# 
```{r}


QMistakes <- QMistakes %>% mutate(time = as.numeric(exam) -1)

currMis <- QMistakes %>% filter(time>0) %>% mutate(currentMistakes = numMistakes) %>% select(-numMistakes)

agdata<- left_join(agdata, currMis, by = c("student_id", "question_id", "time")) %>% select(-exam) %>% mutate(currentMistakes = case_when(is.na(currentMistakes)~0, .default = currentMistakes))

a1 <- agdata %>% filter(attempt ==1)

a2 <- agdata %>% filter(attempt ==2)

a3 <- agdata %>% filter(attempt ==3)
a4 <- agdata %>% filter(attempt ==4)


agdata1 <- agdata %>% filter(time == 1)

agdata2 <- agdata %>% filter(time == 2) %>% filter(question_id == "CV" | question_id == "Interpret")


agdata3 <- agdata %>% filter(time == 3) %>% filter(question_id == "CONFOUND")

agdata4 <- agdata %>% filter(time == 4) %>% filter(question_id == "COMPCV"| question_id == "IVTHREAT" | question_id == "REP")




pMistakes1 <-  QMistakes %>% filter(exam == 1) %>% mutate(time = time + 1) %>% mutate(pastMistakes = numMistakes) %>% select(-numMistakes)

agdata_1 <- left_join(agdata1, pMistakes1, by = c("student_id", "question_id", "time")) %>% select(-exam)%>%  mutate(pastMistakes = case_when(is.na(pastMistakes)~0, .default = pastMistakes)) %>% select(-attempt, -currentMistakes, -numRep)

pMistakes2 <- QMistakes %>% filter(exam == 2) %>% filter(question_id == "CV" | question_id == "Interpret") %>% mutate(time = time + 1) %>% mutate(pastMistakes = numMistakes) %>% select(-numMistakes)

agdata_2 <- left_join(agdata2, pMistakes2, by = c("student_id", "question_id", "time")) %>% select(-exam)%>%  mutate(pastMistakes = case_when(is.na(pastMistakes)~0, .default = pastMistakes)) %>% select(-attempt, -currentMistakes, -numRep)

pMistakes5_ <- QMistakes %>% filter(exam == 3) %>% filter(question_id == "COMPCV" | question_id == "Interpret" ) %>% mutate(time = time + 2) %>% mutate(pastMistakes = numMistakes) %>% select(-numMistakes)



pMistakes3 <- QMistakes %>% filter(exam == 3) %>% filter(question_id == "CONFOUND") %>% mutate(time = time + 1) %>% mutate(pastMistakes = numMistakes) %>% select(-numMistakes)

agdata_3 <- left_join(agdata3, pMistakes3, by = c("student_id", "question_id", "time")) %>% select(-exam)%>%  mutate(pastMistakes = case_when(is.na(pastMistakes)~0, .default = pastMistakes)) %>% select(-attempt, -currentMistakes, -numRep)

pMistakes4 <- QMistakes %>% filter(exam == 4) %>% filter(question_id == "IVTHREAT" | question_id == "REP" ) %>% mutate(time = time + 1) %>% mutate(pastMistakes = numMistakes) %>% select(-numMistakes)

pMistakes4 <- rbind(pMistakes4, pMistakes5_)

agdata_4 <- left_join(agdata4, pMistakes4, by = c("student_id", "question_id", "time")) %>% select(-exam)%>%  mutate(pastMistakes = case_when(is.na(pastMistakes)~0, .default = pastMistakes)) %>% select( -currentMistakes, -numRep, -attempt)




agdata_attempt1 <- rbind(agdata_1, agdata_2, agdata_3, agdata_4) %>% mutate(attempt = 1) %>% select(-time)

agdata <- agdata %>% mutate(newMistakes = currentMistakes - numRep)

agdata_temp1 <- left_join(agdata, agdata_attempt1, by = c("student_id", "question_id", "attempt")) # append attempt1 to full data 








agdata_a1 <- agdata_temp1 %>% filter(attempt == 1) %>% mutate(attempt = attempt + 1) %>% select(-currentMistakes, -time, -numRep) %>% filter(question_id == "OPDEF" | question_id == "CV" | question_id == "Interpret" | question_id == "COMPCV" | question_id == "CONFOUND" ) #pull out only questions that are repeated again and just grab the new and past mistakes for the next attempt 


agdata_temp2 <- left_join(agdata_temp1, agdata_a1, by = c("student_id", "question_id", "attempt"), suffix = c("", "-1")) # add lagged to the attempt 2 rows 

agdata_attempt2 <- agdata_temp2 %>% filter(attempt ==2) %>% mutate(pastMistakes = `newMistakes-1`+`pastMistakes-1`) %>% select(-`newMistakes-1`, -`pastMistakes-1`, -newMistakes, -currentMistakes, -numRep) %>% select(student_id, question_id, pastMistakes, attempt) # pullout only attempt 2 rows and calculated the past mistakes on "attempt 1' 




agdata_temp3 <- left_join(agdata, agdata_attempt2, by = c("student_id", "question_id", "attempt"), suffix = c("", "-1")) # append attempt2 to full data 

a2 <- agdata_temp3 %>% filter(attempt == 2)


#########STUCK HERE!!!!!! 

#a3test <- agdata %>% filter(attempt == 3)


agdata_a2 <- agdata_temp3 %>% filter(attempt == 2) %>% mutate(attempt = attempt + 1) %>% select(-currentMistakes, -time, -numRep) %>% filter(question_id == "OPDEF" | question_id == "CV" ) #pull out only questions that are repeated again and just grab the new and past mistakes for the next attempt 


agdata_temp4 <- left_join(agdata_temp3, agdata_a2, by = c("student_id", "question_id", "attempt"), suffix = c("", "-1")) # add lagged to the attempt 3 rows 


a3 <- agdata_temp4 %>% filter(attempt ==3)


agdata_attempt3 <- agdata_temp4 %>% filter(attempt ==3) %>% mutate(pastMistakes = `newMistakes-1`+`pastMistakes-1`) %>% select(-`newMistakes-1`, -`pastMistakes-1`, -newMistakes, -currentMistakes, -numRep) %>% select(student_id, question_id, pastMistakes, attempt) # pullout only attempt 3 rows and calculated the past mistakes on "attempt 2' 

test <- rbind(agdata_attempt1, agdata_attempt2, agdata_attempt3)


agdata_temp5 <- left_join(agdata, agdata_attempt3, by = c("student_id", "question_id", "attempt"), suffix = c("", "-1")) # append attempt3 to full data


agdata_a3 <- agdata_temp5 %>% filter(attempt == 3) %>% mutate(attempt = attempt + 1) %>% select(-currentMistakes, -time, -numRep) %>% filter(question_id == "OPDEF") #pull out only questions that are repeated again and just grab the new and past mistakes for the next attempt 


agdata_temp6 <- left_join(agdata_temp5, agdata_a3, by = c("student_id", "question_id", "attempt"), suffix = c("", "-1")) # add lagged to the attempt 4 rows

agdata_attempt4 <- agdata_temp6 %>% filter(attempt ==4) %>% mutate(pastMistakes = `newMistakes-1`+`pastMistakes-1`) %>% select(-`newMistakes-1`, -`pastMistakes-1`, -newMistakes, -currentMistakes, -numRep) %>% select(student_id, question_id, pastMistakes, attempt)  # pullout only attempt 4 rows and calculated the past mistakes on "attempt 3' 

all_attempts <- rbind(agdata_attempt1, agdata_attempt2, agdata_attempt3, agdata_attempt4)

agdata<- left_join(agdata, all_attempts, by = c("student_id", "question_id", "attempt"), suffix = c("1", "2"))


agdata <- agdata %>% mutate(pRep = case_when(pastMistakes == 0 ~ NA, .default = numRep/pastMistakes) ) %>% mutate(numRep = case_when(pastMistakes == 0 ~ NA, .default = numRep) )


write.csv(agdata, "finalMistakesData.csv", row.names = F)


```




DID NOT WORK 
____________________________________________________________
#Time 1  
```{r}
# time 1 repeated mistakes by Notation 

repMistakes1 <- time1data %>% group_by(student_id, question_id, Notation) %>% summarise(
  timesRep = n()-1, #number of repeats
  tot = n() #total number of times each rubric item is given 
) %>% mutate(isRep = case_when(timesRep > 1 ~ 1, .default = timesRep)) #is repeated at least on at least 1 exam 

view(repMistakes1)


#Rep Mistakes per question
QRepMistakes1 <- repMistakes1 %>% group_by(student_id, question_id) %>% summarise(
  numRep = sum(isRep), #number of mistakes that were previously given feedback on 
  totRep = sum(timesRep), #number of repeated items across the exams 
  numTot = sum(tot)# total number of mistakes made across both exams (including repeated items) 
)

QRepMistakes1 <- QRepMistakes1 %>% mutate(uniqueTot = numTot - totRep)


QRepMistakes1 <- QRepMistakes1 %>% mutate(exam = 2)

view(QRepMistakes1)

```



#Time 2  
```{r}
# time 2 repeated mistakes by Notation 

repMistakes2 <- time2data %>% group_by(student_id, question_id, Notation) %>% summarise(
  timesRep = n()-1, #number of repeats
  tot = n() #total number of times each rubric item is given 
) %>% mutate(isRep = case_when(timesRep > 1 ~ 1, .default = timesRep)) #is repeated at least on at least 1 exam 

view(repMistakes2)


#Rep Mistakes per question
QRepMistakes2 <- repMistakes2 %>% group_by(student_id, question_id) %>% summarise(
  numRep = sum(isRep), #number of mistakes that were previously given feedback on 
  totRep = sum(timesRep), #number of repeated items across the exams 
  numTot = sum(tot)# total number of mistakes made across both exams (including repeated items) 
)

QRepMistakes2 <- QRepMistakes2 %>% mutate(uniqueTot = numTot - totRep)


QRepMistakes2 <- QRepMistakes2 %>% mutate(exam = 3) 


view(QRepMistakes2)





```


#Time 3  
```{r}
# time 3 repeated mistakes by Notation 

repMistakes3 <- time3data %>% group_by(student_id, question_id, Notation) %>% summarise(
  timesRep = n()-1, #number of repeats
  tot = n() #total number of times each rubric item is given 
) %>% mutate(isRep = case_when(timesRep > 1 ~ 1, .default = timesRep)) #is repeated at least on at least 1 exam 

view(repMistakes3)


#Rep Mistakes per question
QRepMistakes3 <- repMistakes3 %>% group_by(student_id, question_id) %>% summarise(
  numRep = sum(isRep), #number of mistakes that were previously given feedback on 
  totRep = sum(timesRep), #number of repeated items across the exams 
  numTot = sum(tot)# total number of mistakes made across both exams (including repeated items) 
)

QRepMistakes3 <- QRepMistakes3 %>% mutate(uniqueTot = numTot - totRep)


QRepMistakes3 <- QRepMistakes3 %>% mutate(exam = 4)


view(QRepMistakes3)

```


#Time 4  
```{r}
# time 3 repeated mistakes by Notation 

repMistakes4 <- time4data %>% group_by(student_id, question_id, Notation) %>% summarise(
  timesRep = n()-1, #number of repeats
  tot = n() #total number of times each rubric item is given 
) %>% mutate(isRep = case_when(timesRep > 1 ~ 1, .default = timesRep))

view(repMistakes4)


#Rep Mistakes per question
QRepMistakes4 <- repMistakes4 %>% group_by(student_id, question_id) %>% summarise(
  numRep = sum(isRep), #number of mistakes that were previously given feedback on 
  totRep = sum(timesRep), #number of repeated items across the exams 
  numTot = sum(tot)# total number of mistakes made across both exams (including repeated items) 
)

QRepMistakes4 <- QRepMistakes4 %>% mutate(uniqueTot = numTot - totRep)

QRepMistakes4 <- QRepMistakes4 %>% mutate(exam = 5)

view(QRepMistakes4)






```



##Combine the Data 

```{r}

fullRepMistakes <- full_join(QRepMistakes1, QRepMistakes2, by = c("student_id", "question_id"), suffix = c("1", "2")) #%>% mutate(numRep2 = numRep2-numRep1)



aggregatedData <- QMistakes


```

