---
title: "CleaningTestScript"
author: "Sydney Wood"
date: "2024-06-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load Packages 
```{r}
library(tidycode)
library(tibble)
library(dplyr)
library(tidyverse)
setwd("~/Documents/GitHub/MC_data_cleaning")
```


## Demographic Cleaning

```{r}
dem_data_raw <- read.csv(file = "Raw_dem_data_anon.csv")
dem_data_short <- dem_data_raw %>% select("anon_id", "consent", contains(".."))

colnames(dem_data_short) <- c("anon_id", "consent", "age", "year", "gender", "int_student", "esl", "e_exp", "e_lvl", "URM", "p_education", "m_education", "par_rel", "fin_support", "ses", "grant", "soc_med", "hw_time", "transfer")
```

## Change the categorical data to factors
```{r}
dem_data<- dem_data_short %>% mutate_at(c(4,5,6,7,10,13,15,16,19), factor)
```

## consent
```{r}
dem_data_clean <- dem_data %>%
  mutate(consent = case_when(
    grepl("I do not consent", consent, fixed = TRUE) ~ 0,
    grepl("I consent to participate", consent, fixed = TRUE) ~ 1,
    TRUE ~ 0))



dem_data_clean <- dem_data_clean %>%
  filter(consent == 1)
```

## there is a 2002 in age column.

## year
```{r}
dem_data_clean <- dem_data_clean %>%
  mutate(year = case_when(
    grepl("Freshman", year, fixed = TRUE) ~ 1,
    grepl("Sophomore", year, fixed = TRUE) ~ 2,
    grepl("Jonior", year, fixed = TRUE) ~ 3,
    grepl("Senior", year, fixed = TRUE) ~ 4,
    TRUE~NA
  ))
```

## Gender
```{r}
dem_data_clean <- dem_data_clean %>%
  mutate(gender = case_when(
    grepl("Woman", gender, fixed = TRUE) ~ 'Woman',
    grepl("Man", gender, fixed = TRUE) ~ 'Man',
    grepl("Non-binary or Genderqueer", gender, fixed = TRUE) ~ 'Other',
    TRUE~NA
  ))
```

## int_student
```{r}
dem_data_clean <- dem_data_clean %>%
  mutate(int_student = case_when(
    grepl("Yes", int_student, fixed = TRUE) ~ 1,
    grepl("No", int_student, fixed = TRUE) ~ 0,
    TRUE~NA
  ))
```

## esl
```{r}
dem_data_clean <- dem_data_clean %>%
  mutate(esl = case_when(
    grepl("English is my first language", esl, fixed = TRUE) ~ 1,
    grepl("English is not my first language", esl, fixed = TRUE) ~ 0,
    TRUE~NA
  ))
```

## e_lvl
```{r}
dem_data_clean <- dem_data_clean %>%
  mutate(e_lvl = case_when(
    grepl("0", e_lvl, fixed = TRUE) ~ 0,
    grepl("1", e_lvl, fixed = TRUE) ~ 1,
    grepl("2", e_lvl, fixed = TRUE) ~ 2,
    grepl("3", e_lvl, fixed = TRUE) ~ 3,
    grepl("4", e_lvl, fixed = TRUE) ~ 4,
    grepl("5", e_lvl, fixed = TRUE) ~ 5, 
    grepl("6", e_lvl, fixed = TRUE) ~ 6, 
    TRUE~NA
  ))
```

### URM
```{r}
dem_data_clean <- dem_data_clean %>%
  mutate(URM = case_when(
    grepl("Black or African American", e_lvl, fixed = TRUE) ~ 1,
    grepl("Caucasian", e_lvl, fixed = TRUE) ~ 2, 
    grepl("East or South East Asian", e_lvl, fixed = TRUE) ~ 3,
    grepl("Hispanic or Latino", e_lvl, fixed = TRUE) ~ 4,
    grepl("Middle Eastern or West Asian", e_lvl, fixed = TRUE) ~ 5,
    grepl("Mixed Race", e_lvl, fixed = TRUE) ~ 6,
    grepl("North or Central Asian", e_lvl, fixed = TRUE) ~ 7,
    grepl("Pacific Islander", e_lvl, fixed = TRUE) ~ 8,
    grepl("South Asian", e_lvl, fixed = TRUE) ~ 9,
    TRUE~NA
  ))
```

