---
title: "2023 Data"
author: "Xinhui Zhang"
date: "2024-10-04"
output: html_document
---

```{r}
setwd("~/Documents/GitHub/MC_data_cleaning")
getwd()
```



```{r}
setwd("~/Documents/GitHub/MC_data_cleaning")
grades <- read.csv(file ="wq_grades_final.csv")

dem <- read.csv("First_dataset.csv")

final_grades <- grades %>% select(-"anon_id")

final_data <- full_join(dem,grades, by = "anon_id")

final_data <- final_data %>% filter(!is.na(consent))

final_data <- final_data %>% select(-"consent")
```

```{r}
write.csv(final_data, "2023_initial_dataset.csv", row.names = F)
```

## p_tot1
```{r}
library(dplyr)
setwd("~/Documents/GitHub/MC_data_cleaning/2023 data/new version of exams")
exam1_short <- read.csv("exam1_writtenQs_deleted.csv", sep = ",")
```

```{r}
exam1_calc <- exam1_short %>% select(4:9)
exam1_short <- exam1_short %>%
  mutate(written = rowSums(exam1_calc, na.rm = TRUE))
```

```{r}
exam1_final <- exam1_short %>% mutate(p_tot1 = (written/50)*100) 
```

```{r}
exam1_end <- exam1_final %>% select("anon_id", "views1", "p_tot1")
```

```{r}
final_data <- left_join(final_data, exam1_end, by = "anon_id" )
```


##p_tot2
```{r}
library(dplyr)
exam2_short <- read.csv("exam2_writtenQs_deleted.csv", sep = ",")
```

```{r}
exam2_calc <- exam2_short %>% select(4:7)
exam2_short <- exam2_short %>%
  mutate(written = rowSums(exam2_calc, na.rm = TRUE))
```

```{r}
exam2_final <- exam2_short %>% mutate(p_tot2 = (written/55)*100) 
```

```{r}
exam2_end <- exam2_final %>% select("anon_id", "views2", "p_tot2")
```

```{r}
final_data <- left_join(final_data, exam2_end, by = "anon_id" )
```

##p_tot3
```{r}
library(dplyr)
exam3_short <- read.csv("exam3_writtenQs_deleted.csv", sep = ",")
```

```{r}
exam3_calc <- exam3_short %>% select(4:7)
exam3_short <- exam3_short %>%
  mutate(written = rowSums(exam3_calc, na.rm = TRUE))
```

```{r}
exam3_final <- exam3_short %>% mutate(p_tot3 = (written/35*100))
```

```{r}
exam3_end <- exam3_final %>% select("anon_id", "views3", "p_tot3")
```

```{r}
final_data <- left_join(final_data, exam3_end, by = "anon_id" )
```


##p_tot4
```{r}
library(dplyr)
exam4_short <- read.csv("exam4_writtenQs_deleted.csv", sep = ",")
```

```{r}
exam4_calc <- exam4_short %>% select(4:8)
exam4_short <- exam4_short %>%
  mutate(written = rowSums(exam4_calc, na.rm = TRUE))
```

```{r}
exam4_final <- exam4_short %>% mutate(p_tot4 = (written/50)*100) 
```

```{r}
exam4_end <- exam4_final %>% select("anon_id", "views4", "p_tot4")
```

```{r}
final_data <- left_join(final_data, exam4_end, by = "anon_id" )
```

##p_tot5
```{r}
library(dplyr)
exam5_short <- read.csv("exam5_writtenQs_deleted.csv", sep = ",")
```

```{r}
exam5_calc <- exam5_short %>% select(4:9)
exam5_short <- exam5_short %>%
  mutate(written = rowSums(exam5_calc, na.rm = TRUE))
```

```{r}
exam5_final <- exam5_short %>% mutate(p_tot5 = (written/60)*100) 
```

```{r}
exam5_end <- exam5_final %>% select("anon_id", "views5", "p_tot5")
```

```{r}
final_data <- left_join(final_data, exam5_end, by = "anon_id" )
```

```{r}
write.csv(final_data, "2023_cleaned.csv", row.names = F)
```




